- name: Add workers to inventory
  hosts: localhost
  gather_facts: false
  vars: {}
  tasks:

    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Create group workers with workers' IPs
      add_host:
        name: "{{ item }}"
        groups: workers
        ansible_user: ubuntu
        ansible_connection: ssh
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_become: yes
      loop: '{{ worker_ip_addresses }}'


- name: Set up connection between jumphost and workers
  hosts: workers
  gather_facts: false
  vars: {}
  tasks:

    - name: Configure workers
      include: workers.yml
