- name: Update inventory with worker IPs
  hosts: localhost
  gather_facts: false
  vars: {}
  tasks:

    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Add worker {{ worker_idx }} to inventory
      add_host:
        name: "{{ worker_ip_address }}"
        groups: workers
        ansible_user: ubuntu
        ansible_connection: ssh
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_become: yes

- name: Setup connection to workers
  hosts: workers
  gather_facts: false
  vars: {}
  tasks:

    - name: Configure workers
      include: workers.yml
