---
- name: Create /etc/fsspec directory
  file:
    path: /etc/fsspec
    state: directory
    mode: '0755'
- name: Create FSSPEC config file
  copy:
    dest: /etc/fsspec/dcache.json
    content: {{ dcache_config | to_json }}
    state: file
- name: Export path to FSSPEC config file
  lineinfile:
    path: /etc/environment
    line:  FSSPEC_CONFIG_DIR=/etc/fsspec
    regexp: '^FSSPEC_CONFIG_DIR=/etc/fsspec'
