galaxy_info:
  author: Francesco Nattino
  description: JupyterDask SRC dcache tasks
  company: Netherlands eScience Center
  license: Apache-2.0
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
dependencies: []