name: jupyter_dask
channels:
  - conda-forge
dependencies:
  - python=3.9
  - asyncssh
  - dask[complete]
  - python-graphviz
  - jupyterhub
  - jupyterhub-idle-culler
  - jupyterhub-systemdspawner
  - jupyterlab
  - dask-labextension
  - jupyterlab-geojson
  - jupyterlab-git
  - jupyter-server-proxy
  - pip
