name: jupyter_dask
channels:
  - conda-forge
dependencies:
  - asyncssh
  - bokeh<3  # issues with the Dask dashboard
  - click==8.0.2  # temporary fix until https://github.com/dask/distributed/issues/6013 is released
  - fsspec==2023.12.2  # fix until https://github.com/NLeSC-GO-common-infrastructure/dcachefs/issues/19
  - dask[complete]
  - python-graphviz
  - jupyterhub
  - jupyterhub-idle-culler
  - jupyterhub-systemdspawner
  - jupyterlab
  - dask-labextension
  - jupyterlab-geojson
  - jupyterlab-git
  - jupyter-server-proxy
  - pip
  - pip:
      - dcachefs
