galaxy_info:
  author: Stefan Verhoeven, Peter Kalverla and Francesco Nattino
  description: JupyterDask SRC conda tasks
  company: Netherlands eScience Center
  license: Apache-2.0
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags: []
dependencies: []
